name: build-www
on: 
  push:
    branches: [ main ]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: Build Rust
      run: |
        cargo install
        wasm-pack build
    
    - name: Build Site
      run: |
        cd www
        npm run build
